### ISSUE TITLE
libfftw3 not listed in apt-get

### ISSUE THREAD

**Issue by jonathantompson** [soumith/torch-signal#4]
On ubuntu I had to use:

sudo apt-get install libfftw3-3

not

sudo apt-get install libfftw3

Thanks for putting this together :-)  I don't suppose you've already implemented image deconvolutions (using Wiener deconvolutions)?

**Comment by BassmanBiff** [comment]
I'm getting this issue on Mint 18.1. Apt package name is libfftw3-3, libraries installed are below. Trying to install the rock gives "Missing dependencies for signal: fftw3 >= 1.0". Not sure if there's something I should be doing differently.

/usr/lib/x86_64-linux-gnu/libfftw3l_omp.so
/usr/lib/x86_64-linux-gnu/libfftw3l.so
/usr/lib/x86_64-linux-gnu/libfftw3f.so
/usr/lib/x86_64-linux-gnu/libfftw3.so
/usr/lib/x86_64-linux-gnu/libfftw3q_omp.so
/usr/lib/x86_64-linux-gnu/libfftw3_threads.so
/usr/lib/x86_64-linux-gnu/libfftw3f_threads.so
/usr/lib/x86_64-linux-gnu/libfftw3q.so
/usr/lib/x86_64-linux-gnu/libfftw3_omp.so
/usr/lib/x86_64-linux-gnu/libfftw3l_threads.so
/usr/lib/x86_64-linux-gnu/libfftw3f_omp.so
/usr/lib/x86_64-linux-gnu/libfftw3q_threads.so
