### ISSUE TITLE
FFTW is GPL — Licensing Issues?

### ISSUE THREAD

**Issue by alexbw** [soumith/torch-signal#5]
Torch Signal and Torch Audio both link against FFTW, which is GPL code. 
The licenses for the Lua libraries is BSD. I'm not an expert in this stuff, but I just wanted to confirm that since FFTW is not being _distributed_ with this software, there is no problem?

**Comment by soumith** [comment]
This is not a problem wrt licensing. Linking non-statically is acceptable for GPL afaik.
